stages:
  - build
  - security

build:
  image: node:20
  stage: build
  script:
    - echo "Building webhook-service..."
    - cd webhook
    - npm ci || npm install
    - npm run build --if-present
    - cd ..

    - echo "Building back-devmaterial..."
    - cd back-devmaterial
    - npm ci || npm install
    - npm run build --if-present
    - cd ..

    - echo "Building front-devmaterial..."
    - cd front-devmaterial
    - npm ci || npm install
    - npm run build --if-present

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: security
  needs: ["build"]
  variables:
    SAST_EXCLUDED_PATHS: "node_modules,dist"
    SAST_ANALYZER_IMAGE_TAG: "latest"
  allow_failure: false