apiVersion: 1

datasources:
  - name: bdd webhook
    type: postgres
    access: proxy
    url: webhook-db:5432
    user: webhook
    secureJsonData:
      password: webhook
    database: webhook_db
    isDefault: true
    jsonData:
      sslmode: "disable"
