{
 "title": "Suivi DevMateriels",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Nombre de devis",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS nombre_devis FROM devis;"
    }
   ]
  },
  {
   "title": "Évolution des devis dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_creation AS \"time\", SUM(montant) AS total_montant\r\nFROM devis\r\nGROUP BY date_creation\r\nORDER BY date_creation;"
    }
   ]
  },
  {
   "title": "Moyenne du montant des devis (€)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(montant) AS moyenne_devis FROM devis;"
    }
   ]
  },
  {
   "title": "Montants par client",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT client, SUM(montant) AS total_montant\r\nFROM devis\r\nGROUP BY client\r\nORDER BY total_montant DESC;"
    }
   ]
  }
 ]
}