{
 "title": "Suivi des logs",
 "time": { "from": "2025-10-14T01:45:32.422Z", "to": "2025-10-18T01:45:32.422Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Nombre total de webhooks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) AS total_webhooks\r\nFROM event_results;"
    }
   ]
  },
  {
   "title": "Nombre d’erreurs par heure",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', created_at) AS heure, COUNT(*) AS erreurs\r\nFROM event_results\r\nWHERE status != 'ok'\r\nGROUP BY heure\r\nORDER BY heure;\r\n"
    }
   ]
  },
  {
   "title": "Taux de réussite des webhooks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(\r\n    (SUM(CASE WHEN status = 'ok' THEN 1 ELSE 0 END)::decimal / COUNT(*)) * 100,\r\n    2\r\n  ) AS taux_succes\r\nFROM event_results;"
    }
   ]
  },
  {
   "title": "Latence moyenne des webhooks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  ROUND(AVG(EXTRACT(EPOCH FROM (er.created_at - e.sent_at)))::numeric, 2) AS moyenne_latence_secondes\r\nFROM event_results er\r\nJOIN events e ON er.event_id = e.id;"
    }
   ]
  },
  {
   "title": "Nombre total d’abonnés actifs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_abonnes FROM subscribers;"
    }
   ]
  }
 ]
}