name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ==========================================
  #  1️⃣ BUILD STAGE
  # ==========================================
  build:
    name: Build ${{ matrix.project }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        project: [webhook, back-devmaterial, front-devmaterial, back-wagonlits, front-wagonlits]
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json
      - name: Build ${{ matrix.project }}
        run: |
          echo "🚀 Building ${{ matrix.project }}..."
          npm ci || npm install
          npm run build --if-present

  # ==========================================
  #  2️⃣ SECURITY STAGE (SAST / CodeQL)
  # ==========================================
  security:
    name: Security Scan (SAST / CodeQL)
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [build]
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ==========================================
  #  3️⃣ TEST STAGE
  # ==========================================
  test:
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [security]
    strategy:
      matrix:
        project: [back-devmaterial]
        #project: [webhook, back-devmaterial, front-devmaterial, back-wagonlits, front-wagonlits]
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json
      - name: Run tests
        run: |
          echo "🧪 Testing ${{ matrix.project }}..."
          npm ci || npm install
          npm test --if-present
